### ISSUE TITLE
お部屋のスコア入力ページを作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#10]
## 概要
お部屋のスコア入力ページのひな形を作成する。

※以下の項目は別Issueにて対応。
* デザイン

## 内容
- [ ] Scoreコントローラのひな形を作成
- [ ] Scoreコントローラにnew, createアクションを追加
- [ ] RoomモデルとScoreモデルを関連付けする
- [ ] ページに「入力者（名前・ニックネーム）」を作成
- [ ] ページに各評価項目を作成
- [ ] ページに「スコアを保存する」ボタンを作成
- [ ] スコアの保存ボタンを押した後、フラッシュメッセージを表示する
- [ ] 戻るボタンの作成

## ゴール
- [ ] お部屋のスコア入力ページに「入力者（名前・ニックネーム）」、各評価項目、「スコアを保存する」ボタンをそれぞれ表示できている
- [ ] 「スコアを保存する」ボタンを押すと、RoomモデルにひもづいたScoreデータが作成・保存できている
- [ ] 「スコアを保存する」ボタンを押すと、お部屋の内見一覧ページにリダイレクトできている
- [ ] お部屋の内見一覧ページにリダイレクトした後、スコアの登録に関するフラッシュメッセージが表示できている

## 備考
スコア編集ページとほぼ同じ構成になるため、共通化させながら実装していく。

## デザイン
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/0053d0cd-d82e-4d37-9668-328d76bd3b4a" width="200">

**Comment by takuminasu** [comment]
1アクション1issueでお願いします。(new, createは合わせて1つでOK)

**Comment by uchihiro04** [comment]
@takuminasu 
このIssueでのアクションについて、new, createアクションのみを行う形に修正しました。

**Comment by uchihiro04** [comment]
以下のIssueに分割したため、Issueをクローズしました。
- #107 
- #108 
- #109
