### ISSUE TITLE
お部屋のスコア詳細ページを作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#17]
## 概要
お部屋のスコア詳細ページを作成する。

## 内容
- [ ] HouseViewings::Rooms::Scoresコントローラにindexアクションを追加
- [ ] 物件名と合計スコアを表示
- [ ] 評価項目ごとの合計スコアを表示

## ゴール
- [ ] お部屋のスコア詳細ページに物件名・合計スコアが表示されている
- [ ] お部屋のスコア詳細ページに評価項目ごとの合計スコアが表示されている

## デザイン
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/1dbf7653-55ef-4392-85d8-48a5f629ef81.png" width="200">

**Comment by takuminasu** [comment]
>Roomsコントローラにshowアクションを追加

`HouseViewingsScores::Rooms::Scores` コントローラのindexになりますかね？

**Comment by uchihiro04** [comment]
@takuminasu 
> HouseViewingsScores::Rooms::Scores コントローラのindexになりますかね？

ハドルでもご指摘いただいた通り、Pathで考えるとHouseViewings::Rooms::Scores コントローラのindexアクションを使用する形になりますね……。

レビューをもとに、以下の修正を行いました。
- descriptionについて
descriptionの「内容」を以下の形で修正しました。
  - 「 Roomsコントローラにshowアクションを追加」を削除
  - 「 HouseViewings::Rooms::Scoresコントローラにindexアクションを追加」を追加
  
- Pathについて
お部屋のスコア詳細ページのPathを以下の通り修正しました。
修正前：`/house_viewings/:house_viewing_uuid/rooms/:room_id`
修正後：`/house_viewings/:house_viewing_uuid/rooms/:room_id/scores`

  修正内容は以下のIssueの「修正版4（2023/6/19 14:00）」に反映しています。
- #4

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04 デザイン流用できるため0.5で良さそうです

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
ポイントを1→0.5に変更しました。
