### ISSUE TITLE
TOPページを作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#29]
## 概要
TOPページを作成する。TOPページで「はじめる」ボタンを押すと、お部屋の内見一覧ページに遷移する。

## 内容
- [x] Homeコントローラのひな形を作成する
- [x] Homeコントローラのindexアクションを作成する
- [x] 見出し・概要を表示する
- [x] 使い方を表示する
- [x] HouseViewingsコントローラのcreateアクションを追加する
- [x] 「はじめる」ボタンを作成する

## ゴール
- [x] 見出し・概要・使い方を表示できている
- [x] 「はじめる」ボタンを押すとお部屋の内見一覧ページに遷移される

## デザイン
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/07f2b1d4-87d8-49bf-804e-8cfdf7f39cd6" width="200">

**Comment by takuminasu** [comment]
>HouseViewingsコントローラのnew, createアクションを追加する

newは不要です。

**Comment by uchihiro04** [comment]
@takuminasu 
TOPページの「はじめる」ボタンでHouseViewingデータを作成するため、newアクションを使用すると思い込んでいました……。
descriptionの「内容」について以下の通り変更しました。

修正前：HouseViewingsコントローラのnew, createアクションを追加する
修正後：HouseViewingsコントローラのcreateアクションを追加する

---
また、コントローラとアクションについて1点質問させていただければと思います。
**・質問内容**
TOPページの表示に関わるコントローラとアクションはどのような形になりますでしょうか。

**・質問の経緯**
今までTOPページに関してはHouseViewingデータを作成するため、newアクションを使用すると考えていました。
しかしレビューを受け、違うコントローラとアクションを使う必要がありそうだと考えました。

今回の場合TopPagesコントローラのindexアクション、もしくはWelcomesコントローラのindexアクションなどを使用する形になると推測しました。しかし、判断に自信がなかったため質問させていただきました。

**Comment by takuminasu** [comment]
>TOPページの表示に関わるコントローラとアクションはどのような形になりますでしょうか。

一般的なところで言うとHomeControllerのindexアクションですかね。

**Comment by uchihiro04** [comment]
>一般的なところで言うとHomeControllerのindexアクションですかね。

ありがとうございます。HomeだとTOPページに関するコントローラであることが推測しやすそうです。
ハドルでアドバイスいただいた内容も踏まえて、以下の形でdescriptionの修正を行いました。

- 内容に「Homeコントローラのひな形を作成する」を追加
- 内容に「Homeコントローラのindexアクションを作成する」を追加
