### ISSUE TITLE
お部屋の内見一覧ページのひな形を作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#44]
## 概要
お部屋の内見一覧ページのひな形を作成する。

## 内容
- [ ] Roomsコントローラにindexアクションを追加する
- [ ] お部屋の内見一覧ページにRoomデータを10件表示
- [ ] お部屋の内見一覧ページに説明文を追加

## ゴール
- [ ] お部屋の内見一覧ページに10件分のHouseデータを表示できている
- [ ] お部屋の内見一覧ページに説明文を追加できている

## 対応しないこと
1つでまとめて対応するとスコープが大きくなるため、以下は別Issueにて対応。
- 「スコアを見るボタン」の作成
- 「招待URLをコピー」ボタンの作成
- スコア入力数の表示
- 「スコアを見る」ボタンの条件分岐（誰もスコアを入力していない状態で「お部屋のスコア結果ページ」に遷移できないようにする）

## デザイン
<img width="223" alt="image" src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/1dc6620b-f744-49d0-a35f-14b0defd69ac">

**Comment by takuminasu** [comment]
このissueでやることが多いですね。
1アクション1issueぐらいのスコープでお願いします。

**Comment by uchihiro04** [comment]
@takuminasu 
このIssueでは、HouseViewingsコントローラにshowアクションを実装する形に修正しました。

**Comment by uchihiro04** [comment]
@takuminasu
ハドルでの指摘を受け、以下の形でIssueのdescription（内容）を修正しました。

修正前：HouseViewingsコントローラにshowアクションを追加する
修正後：Roomsコントローラにindexアクションを追加する

**Comment by takuminasu** [comment]
>「スコアを見る」ボタンの表示
 「招待URLをコピー」ボタンの表示

ここはissueを分けましょう。

**Comment by uchihiro04** [comment]
@takuminasu 
「スコアを見る」ボタンの表示、「招待URLをコピー」ボタンの表示を別Issueに切り分け、このIssueに含めないようにしました。

**Comment by takuminasu** [comment]
LGTMです。
figmaでデザインもある程度形になっているので以下のような見出しがあってもいいと思いました。

## デザイン
<img width="231" alt="スクリーンショット 2023-06-19 13 29 41" src="https://github.com/uchihiro04/house-viewing-score-log/assets/62975075/4e488456-9eb1-4778-99cf-11fa5d309c64">

## 対応しないこと
- スコアを見る招待URL
  - 1つでまとめて対応するとスコープが大きくなるので別issueにて対応
- 招待URLをコピー
  - 1つでまとめて対応するとスコープが大きくなるので別issueにて対応

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04 1ポイントで大丈夫だと思います

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
ポイントを2→1に修正しました。

**Comment by uchihiro04** [comment]
以下のIssueに分割したため、Issueをクローズしました。
- #99 
- #100 
- #101
