### ISSUE TITLE
お部屋のスコア結果ページのひな形を作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#49]
## 概要
お部屋のスコア結果ページのひな形を作成する。

## 内容
- [x] Scoreコントローラにindexアクションを追加
- [x] 総合スコアの見出し・説明文を作成
- [x] お部屋ごとのスコアの見出し・説明文を作成
- [x] お部屋の総合スコアに、スコアの合計上位2部屋を表示
- [x] 合計スコア上位2部屋について、評価項目ごとの得点を表示する
- [x] お部屋ごとのスコアを表示する

## ゴール
- [x] お部屋のスコア結果ページに総合スコアの見出し・説明文が表示されている
- [x] お部屋のスコア結果ページにお部屋ごとのスコアの見出し・説明文が表示されている
- [x] お部屋の総合スコアに、スコアの合計上位2部屋を表示できている
- [x] 合計スコア上位2部屋の評価項目ごとの得点が表示されている
- [x] お部屋ごとのスコアが表示できている

## 対応しないこと
1つでまとめて対応するとスコープが大きくなるため、以下は別Issueにて対応。
- [ ] 評価項目ごとの得点について、アコーディオンメニューにする

## デザイン
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/ea413497-e109-4524-b937-b9d453feb565.png" width="200">

「上位2件のスコアを比較」に関しては、テーブル表示する形にする（以下のようなイメージ）。
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/bf675843-8566-4a43-8b20-353d5ab83434" width="500">

**Comment by uchihiro04** [comment]
## 判断に迷った箇所
スコア結果ページについて、どのコントローラーのアクションと紐づけるか判断に迷っています。

スコア結果ページでは以下の項目を表示します。
* 総合スコア
上位2件のお部屋の合計スコア、評価項目ごとのスコアを表示し比較する。
* お部屋ごとのスコア
お部屋ごとの合計スコアを表示する

今回の場合、どちらのコントローラーのアクションと紐づけるといいでしょうか。
Pathは`/house_viewings/:house_viewing_uuid/rooms/scores`となります。

1. Scoresコントローラのindexアクション
2. Roomsコントローラのscoresアクション

今回は1でIssueを作成していますが、2のほうがPathを見たときに自然なのかもしれないと思い、判断に迷っています。

**Comment by takuminasu** [comment]
ごめんなさい、レビュー漏れですがpathが間違ってそうです。
`/house_viewings/:house_viewing_uuid/scores`
の方が良さそうです。
アクションは
>Scoresコントローラのindexアクション

こちらで問題ないです。

**Comment by uchihiro04** [comment]
@takuminasu 
お部屋のスコア結果を表示Pathについて、`/house_viewings/:house_viewing_uuid/rooms/scores`から`/house_viewings/:house_viewing_uuid/scores`に変更しました。以下のリンクの「修正版4（2023/6/19 14:00）」に変更を反映しています。
https://github.com/uchihiro04/house-viewing-score-log/issues/4#issuecomment-1555841519

また、アクションにつきまして承知しました。

**Comment by takuminasu** [comment]
>総合スコアに合計スコア上位2部屋を表示する
 合計スコア上位2部屋について、評価項目ごとの得点を表示する
お部屋ごとのスコアを表示する

この3つはこのissue内で対応していいと思います。

**Comment by uchihiro04** [comment]
@takuminasu 
レビューをもとに、descriptionで以下の修正を行いました。
* 「内容」に以下の項目を追加
  * お部屋の総合スコアに、スコアの合計上位2部屋を表示
  * 合計スコア上位2部屋について、評価項目ごとの得点を表示する
  * お部屋ごとのスコアを表示する
* 「ゴール」に以下の項目を追加
  * お部屋の総合スコアに、スコアの合計上位2部屋を表示できている
  * 合計スコア上位2部屋の評価項目ごとの得点が表示されている
  * お部屋ごとのスコアが表示できている
* 追加された内容に応じて、「対応しないこと」の項目を削除

また、項目の追加に伴い、以下のIssueの内容を変更したいと思います。
- #85 
- #87 
それぞれこのIssueに統合されるため、Issueをクローズまたは削除する。
- #86 
内容の変更に伴い、「お部屋ごとのスコアを表示する」から「お部屋ごとのスコアの表示形式を変更する」に名称変更する。
