### ISSUE TITLE
アプリケーションのひな形を作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#68]
## 概要
`rails new`を行い、アプリケーションのひな形を作成する。その際、PostgreSQLとTailwind CSSをインストールする。

## 内容
- [x] `rails new`に不要な機能を調査
- [x] `rails new`を実行（オプションでPostgreSQLとTailwind CSSをインストール）

## ゴール
- [x] Railsを起動し、`http://localhost:3000/`にアクセスしたときに初期画面が表示できている。

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04  0.3でいけると思います

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
環境構築も兼ねている箇所だったため、多めに時間を見積もりすぎました……。
ポイントを1→0.3に変更しました。

**Comment by uchihiro04** [comment]
ひな形の作成についてApproveをいただいたため、Issueをクローズします。
