### ISSUE TITLE
お部屋の内見一覧ページに、スコア入力数を表示する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#79]
## 概要
お部屋の内見一覧ページに、部屋ごとのスコア入力数を表示する。

## 内容
- [ ] お部屋の内見一覧ページに、部屋ごとのスコア入力数を表示する。

## ゴール
- [ ] スコアを入力していない部屋の場合、スコア入力数が0になっている
- [ ] ある部屋のスコアを入力した後、スコア入力数が1増えている。

**Comment by Yuma-Nagaoka** [comment]
0.3→0.1で良さそうです

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
ポイントを0.3→0.1に変更しました。
