### ISSUE TITLE
お部屋のスコア編集ページを作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#82]
## 概要
お部屋のスコア編集ページを作成する。

## 内容
- [x] Scoreコントローラにedit, updateアクションを追加
- [x] アパート名の表示
- [x] 入力者一覧の表示
- [x] 入力者一覧に「新規入力」ボタンを追加
- [x] 入力者（名前・ニックネーム）の表示
- [x] 各評価項目の表示
- [x] 「スコアを更新する」ボタンの作成

## ゴール
- [x] 入力者（名前・ニックネーム）、各評価項目のスコアがそれぞれ表示される
- [x] 「スコアを更新する」ボタンを押すと、更新内容が保存されている
- [x] 再度スコア編集ページにアクセスしたとき、更新後の内容が画面に反映されている
- [x] 入力者一覧の「新規入力」ボタンを押すと、お部屋のスコア入力ページに遷移する

## 対応しないこと
1つでまとめて対応するとスコープが大きくなるため、以下は別Issueにて対応。
- 新規入力画面と編集画面の切り替えの高速化

## デザイン
<img src="https://github.com/uchihiro04/house-viewing-score-log/assets/77523896/c9c8fe2c-c2b5-4399-adda-baae44ac5dd4.png" width="200">

**Comment by takuminasu** [comment]
これは実装するときに意識するといいと思いますが
updateで同じパラメータを更新する想定かつフォームが同じであればnewの時点で共通化を意識した実装をするといいと思います。

**Comment by uchihiro04** [comment]
@takuminasu 
レビューありがとうございます。
いただいたレビューの通り、あらかじめ共通化を意識して実装した方が、後から共通化するより手間が少ないですね。

「お部屋のスコア入力ページ」のIssueのdescription内に、備考として共通化に関する一文を追加しました。
- #10

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04 

画面は
https://github.com/uchihiro04/house-viewing-score-log/issues/10 とほぼ同じため、
このissueでやることは「Scoreコントローラにedit, updateアクションを追加」のみの認識です。
そのため0.5でいいと思います。

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
確かに画面は#10 で共通のものを使うので時間がかからないですね……
ポイントを1→0.5に変更しました。
