### ISSUE TITLE
HouseViewingsコントローラにshowアクションを追加する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#84]
## 概要
HouseViewingsコントローラのひな形を作成し、showアクションを追加する。

## 内容
- [ ] Description::HouseViewingsコントローラのひな形を作成する
- [ ] Description::HouseViewingsコントローラにshowアクションを追加する

## ゴール
- [ ]  Description::HouseViewingsコントローラにshowアクションが追加できている

**Comment by takuminasu** [comment]
これはどこで使用予定ですか？

**Comment by takuminasu** [comment]
descriptionか
Description::HouseViewings#showで認識あってますでしょうか？

**Comment by uchihiro04** [comment]
@takuminasu 
>これはどこで使用予定ですか？

アプリ説明ページ（招待URLからアクセスした人が見るページ）で使用する形になります。

>descriptionか
Description::HouseViewings#showで認識あってますでしょうか？

Pathを考慮して、Description::HouseViewings#showにしようと考えています。descriptionを以下の形で修正しました。
- 内容について
以下の項目を削除しました。
  - HouseViewingsコントローラのひな形を作成する
  - HouseViewingsコントローラにshowアクションを追加する

  以下の項目を追加しました。
  - Description::HouseViewingsコントローラのひな形を作成する
  - Description::HouseViewingsコントローラにshowアクションを追加する

- ゴールについて
以下の項目を削除しました。
  - HouseViewingsコントローラにshowアクションが追加できている

  以下の項目を追加しました。
  - Description::HouseViewingsコントローラにshowアクションが追加できている

---
また、こちらのIssueは以下のIssueと統合しようと思います。統合次第Issueをクローズする予定です。
- #91

**Comment by uchihiro04** [comment]
以下のIssueに項目を統合したため、Issueをクローズします。
- #91
