### ISSUE TITLE
スコア入力ページに「入力者一覧」を作成する

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#88]
## 概要
スコア入力ページに「入力者一覧」を作成する。

## 内容
- [ ] Scoresコントローラのnewアクションの中で入力者の情報を取得
- [ ] スコア入力ページに入力者の一覧を表示
- [ ] 入力者の横に「編集」ボタンを作成

## ゴール
- [ ] Scoresコントローラのnewアクションの中で入力者の情報を取得できている
- [ ] スコア入力ページに「入力者一覧」が作成できている

## 備考
このIssueに取り組んでいる時点ではスコア編集ページを作成していないため、編集ボタンを押してもスコア編集ページには遷移しない。

**Comment by takuminasu** [comment]
>Scoreコントローラにindexアクションが追加できている

indexを追加ではなくnewの中で入力者の情報を取得するが正しいですかね？

**Comment by uchihiro04** [comment]
@takuminasu 
> indexを追加ではなくnewの中で入力者の情報を取得するが正しいですかね？

ご指摘いただいた内容が正しいです。失礼しました。

レビューをもとに、descriptionに以下の修正を行いました。
- 「内容」に以下の項目を追加
  - Scoresコントローラのnewアクションの中で入力者の情報を取得
- 「ゴール」を以下の形に修正  
  -  「Scoreコントローラにindexアクションが追加できている」を削除
  -  「Scoresコントローラのnewアクションの中で入力者の情報を取得できている」を追加

**Comment by uchihiro04** [comment]
@takuminasu 
ハドルでの擦り合わせをもとにdescriptionに以下の項目を追加しました。
- 内容に以下の項目を追加
「新規入力」ボタンを作成

**Comment by takuminasu** [comment]
>「新規入力」ボタンを作成

これは編集時のみ表示で合意取れたと思うので #82 で対応するのがいいと思います。

#10 -> #88 -> #82
の順に対応予定ですよね？

**Comment by uchihiro04** [comment]
@takuminasu 
>これは編集時のみ表示で合意取れたと思うので https://github.com/uchihiro04/house-viewing-score-log/issues/82 で対応するのがいいと思います。

追加するIssueを誤っていました。失礼しました。
「新規入力」ボタンに関する項目について、このIssueから削除し代わりに#82 へ追加しました。追加内容は以下の通りです。
- 内容に以下の項目を追加
入力者一覧に「新規入力」ボタンを追加
- ゴールに以下の項目を追加
入力者一覧の「新規入力」ボタンを押すと、お部屋のスコア入力ページに遷移する

>https://github.com/uchihiro04/house-viewing-score-log/issues/10 -> https://github.com/uchihiro04/house-viewing-score-log/issues/88 -> https://github.com/uchihiro04/house-viewing-score-log/issues/82
の順に対応予定ですよね？

コメントいただいた通り、#10 （お部屋のスコア入力ページを作成する）、#88 （スコア入力ページに「入力者一覧」を作成する）、#82 （お部屋のスコア編集ページを作成する）の順に対応予定です。
