### ISSUE TITLE
「スコアを見る」ボタンの作成

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#89]
## 概要
お部屋の内見一覧ページに「スコアを見る」ボタンを作成する。

## 内容
- [ ] 「スコアを見る」ボタンを表示する
- [ ] 「スコアを見る」ボタンを押すとスコア結果ページに遷移する

## ゴール
- [ ] 「スコアを見る」ボタンを押すとスコア結果ページに遷移される

**Comment by Yuma-Nagaoka** [comment]
0.3→0.1でいいと思います。

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
ポイントを0.3→0.1に変更しました。
