### ISSUE TITLE
「招待URLをコピー」ボタンの作成

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#90]
## 概要
「招待URLをコピー」ボタンを作成する。ボタンを押すと招待URLをクリップボードにコピーすることができる。

## 内容
- [x] 「招待URLをコピー」ボタンを表示
- [x] 「招待URLをコピー」を押すと`/description/house_viewings/:house_viewing_uuid`がコピーされる

## ゴール
- [x] 「招待URLをコピー」を押した後、`/description/house_viewings/:house_viewing_uuid`をペーストできる状態になっている

## 備考
クリップボードにコピーする場合、JavaScriptでコードを書く必要がある。Rails7の場合Hotwire周りを使う形になると想定される。

**Comment by Yuma-Nagaoka** [comment]
hotwireの導入も含めて1ポイントの想定

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
>hotwireの導入も含めて1ポイントの想定

コメントいただいた通り、Hotwire周りの導入・設定も含めて1ポイントで考えていました。今までHotwire周りに触れることがなかったため、時間がある程度かかるのではという想定です。
