### ISSUE TITLE
アプリ説明ページ（招待URLからアクセスした人が見るページ）を作成

### ISSUE THREAD

**Issue by uchihiro04** [uchihiro04/house-viewing-score-log#91]
## 概要
招待URLからアクセスすると見ることのできるアプリ説明ページを作成する。

## 内容
- [ ] Description::HouseViewingsコントローラのひな形を作成する
- [ ] Description::HouseViewingsコントローラにshowアクションを追加する
- [ ] 見出し・概要を表示する
- [ ] 使い方を表示する
- [ ] 「スコアを入力する」ボタンを作成する

## ゴール
- [ ]  Description::HouseViewingsコントローラにshowアクションが追加できている
- [ ] 見出し・概要・使い方を表示できている
- [ ] 「スコアを入力する」ボタンを押すとお部屋の内見一覧ページに遷移される

## デザイン
<img src="https://user-images.githubusercontent.com/77523896/246778389-0dd0514f-6bd4-43f8-91d4-07c514a6c433.png" width="200">

**Comment by takuminasu** [comment]
https://github.com/uchihiro04/house-viewing-score-log/issues/84 でまとめて対応しましょう。

**Comment by uchihiro04** [comment]
@takuminasu 
>https://github.com/uchihiro04/house-viewing-score-log/issues/84 でまとめて対応しましょう。

このIssueにhttps://github.com/uchihiro04/house-viewing-score-log/issues/84 のIssueを統合する形でもよろしいでしょうか。
理由としては、アプリ説明ページ作成の流れの1つとして、Description::HouseViewings#showの作成があると考えているためです。

追記（2023/6/20 15:20）
#84 のIssueを統合しました。

**Comment by uchihiro04** [comment]
descriptionの内容・ゴールにDescription::HouseViewingsコントローラに関する項目をそれぞれ追加しました。

追加した項目
- 内容
  - Description::HouseViewingsコントローラのひな形を作成する
  - Description::HouseViewingsコントローラにshowアクションを追加する
- ゴール
  - Description::HouseViewingsコントローラにshowアクションが追加できている

**Comment by Yuma-Nagaoka** [comment]
@uchihiro04 TOPページの画面からほぼ流用できると思うので、0.1でいいと思います

**Comment by uchihiro04** [comment]
@Yuma-Nagaoka 
確かにこのIssueで新たに行うことは、Description::HouseViewingsコントローラに関する部分だけですね……。
ポイントを1→0.1に変更しました。
